### ISSUE TITLE
Pls add ID tab

### ISSUE THREAD

**Issue by Makein** [jhonhenry10/NPS_Browser#18]
Add tab for it, bcs when new dlc come out there no way to check what you already installed\downloaded
Or, well, if its grab info from sony then make it show content id info for it too
Thanks

**Comment by IcySon55** [comment]
If you select to delete the PKG in the options, there's no way for the software to know that you already downloaded something. There's especially no way currently to know if you installed it.

**Comment by Sosenek** [comment]
Maybe you can add option to create some file with list of downloaded TitleID and put some extra symbol or different text color on list ? 
I know it's not perfect but can work.

**Comment by Makein** [comment]
Nice idea, if it colored after we downloaded in green it would be great and save track of what we have in txt file + manually color option

**Comment by IcySon55** [comment]
@Makein The implementation of this feature as described is suspect.

* If we just keep a list, does that mean the program doesn't scan directories for the PKG/app files/folders?
* If you want it to scan the files/folders to verify, well it can't really verify the extracted files, because we allow pkg_dec to extract anywhere you want via command line parameters.
* So then we're left with scanning for the PKG, but that means you'll always have two copies of a game on your HDD taking up double the space.

Soooo, what exactly are you after?

@jhonhenry10 Please excuse my use of 'we', it just makes typing the questions out easier.

**Comment by Sosenek** [comment]
I think the file with list of completed (downloaded and unpacked) will be the best solution. 
Probably most people will delete original PKG file anyway and keep unpacked folder or ZIP with activation file inside.
But please implement some symbol or color on list so we don't end up just with txt file with list of downloaded games. 
Or maybe if it's possible to add additional filter to hide already completed position from list will be great.

**Comment by IcySon55** [comment]
@Sosenek Maybe you didn't catch the issue I proposed. If we simply implemented a list of downloaded games, because of the way unpacking works, we could only track past downloads the whether or not they finished downloading and also if they finished unpacking.

This text file would not be able to know:
* When you delete a game
* If the unpacking actually failed or succeeded, only that it *finished*

If we only implement this tracking as a statically changing list that does not reflect what you have on your hard drive, then there will need to be a way on the UI to undo the status of an item (instead of just deleting the .txt) in the case where you want to download it again for any number of reasons.

**Comment by Sosenek** [comment]
Yes I get that program can't know that We delete or keep file on HDD. 
And unfortunately it's one of the things we can't do anything about it. 
This is why I propose to add option to filter it (as checkbox) so, if someone want to download some position again he can unchecked it and will see all position.
Maybe CheckBox next to region list (Filter) ?
About changing status I was thinking about add option in context menu (Right Click) to Mark/Unmark as Completed. 

About second part 
As program have progress as: Download -> Unpacking - > Completed I was sure pkg_dec when finish return failed or success so We can add PCSB... to file as Completed only when pkg_dec return success.
If pkg_dec don't return anything then I think adding to the list should be done when download is completed. 

I'm aware that all above isn't perfect but at the moment I don't think so we can implement anything better.

P.S.
Sorry for my English, I do my best 😄

**Comment by IcySon55** [comment]
I ask these questions not because I think it's a bad idea, but because I want to know how good you expect the feature to be considering the limitations that I outline. On that note, you've done well to answer those questions. It tells me that you would be happy with a mostly manual approach to managing the list of downloaded games where the application is only aware of the fact that a game was downloaded and potentially unpacked (hinging on pkg_dec errors codes and our ability to detect them).

Thanks.

**Comment by jhonhenry10** [comment]
Colors of downloaded Irena are implemented. Hope it fills your request.
